### ISSUE TITLE
Possible bug: Random incineration failures when polymorphic associations are involved

### ISSUE THREAD

**Issue by chiraggshah** [bigbinary/org_incineration#13]
https://www.loom.com/share/83ecdcc3c57a4678919ebd1409303688

To try on local: 
For folks who want to try it out on their local, the branch is `185-add-tests-for-incineration-service` in neeto-crm and the seed value for the failure case is 55054

**Comment by unnitallman** [comment]
@shreyansh-g24 _a

**Comment by shreyansh-g24** [comment]
@chiraggshah Thank you for the bug report
