### ISSUE TITLE
Check the copy (text) that Basecamp displays to a user when he/she deletes his organization

### ISSUE THREAD

**Issue by unnitallman** [bigbinary/org_incineration#14]
Create a Basecamp account and try to delete it. Copy the text that is displayed to the user. We need to use the same on neetoAuth.

@shreyansh-g24 _a

**Comment by shreyansh-g24** [comment]
<img width="1792" alt="Screenshot 2022-02-22 at 5 15 52 PM" src="https://user-images.githubusercontent.com/40631571/155125984-7d811d5a-b829-49f0-b387-97034466e340.png">

**Comment by shreyansh-g24** [comment]
@unnitallman The neetoauth.net close account page already shows this text

**Comment by shreyansh-g24** [comment]
@unnitallman _a

**Comment by shreyansh-g24** [comment]
@neerajdotname Please check the Close Account UI that we have here https://bigbinaryy.neetoauth.net/organization-settings?tab=Close%20my%20account.

To implement the basecamp style UI, 
  - should I create a new route so that close account button would render that route, or
  - implement the basecamp style centered UI on the same page?

**Comment by neerajdotname** [comment]
@shreyansh-g24 I don't have access to that org.

**Comment by shreyansh-g24** [comment]
<img width="1792" alt="Screenshot 2022-03-04 at 11 55 51 AM" src="https://user-images.githubusercontent.com/40631571/156711087-e04878ec-2edf-45f2-b6f9-1f0b292e146f.png">

@neerajdotname Please check.

**Comment by neerajdotname** [comment]
@shreyansh-g24 I'm not following the question. The UI is already looking good. So what's the issue.

**Comment by shreyansh-g24** [comment]
@neerajdotname It was regarding changes to the Close account UI to make it similar to Basecamp close account. Since it is good, I'll close this issue.
