### ISSUE TITLE
Ensure that org incineration is triggered only after 30 days since the account deletion is triggered

### ISSUE THREAD

**Issue by unnitallman** [bigbinary/org_incineration#15]
When the account has been "deleted" by the user, we should only be marking it as deleted in some way, and trigger the org incineration only after 30 days. 

Discuss this with @ghousemohamed - this might already have been implemented. If so, set the period to 2 days on staging and see if incineration works as expected after 2 days.

@shreyansh-g24 _a

**Comment by shreyansh-g24** [comment]
@ghousemohamed _a Has this already been implemented?

**Comment by ghousemohamed** [comment]
@shreyansh-g24 yes, this is done. To change the value to 2 days, you have to do it in neetoauth

**Comment by shreyansh-g24** [comment]
Ok

**Comment by shreyansh-g24** [comment]
@ghousemohamed Why is organization being explicitly destroy here, shouldn't we only be incinerating it?

https://github.com/bigbinary/neeto-auth-web/blob/master/app/workers/organizations_cleanup_worker.rb

**Comment by shreyansh-g24** [comment]
@unnitallman Wouldn't it be better to incinerate and test deletion in a test/via console. More data could've been added in 2 days.

**Comment by shreyansh-g24** [comment]
@unnitallman _a @ghousemohamed _a

**Comment by ghousemohamed** [comment]
@shreyansh-g24 The incineration does not destroy the organization, only the associated associations I believe are destroyed. That's why we have to explicitly call destroy! on the organization after incineration is done.

**Comment by shreyansh-g24** [comment]
@ghousemohamed The Organization model is being skipped in the incinerable_concern because of which, possibly, it is not being destroyed.

**Comment by unnitallman** [comment]
@shreyansh-g24 _a

1. Testing from within the console will be enough since now we know that neetoAuth is handling the scheduling.
2. You can try removing `Organization` from the skipped_models. 
3. For testing, I will get you databases from all the apps which are having some real data. Let us try incineration on each of them. Please mention this during our standup call.

**Comment by shreyansh-g24** [comment]
Tests added for neeto apps.
