### ISSUE TITLE
Add setup to record incinerations

### ISSUE THREAD

**Issue by shreyansh-g24** [bigbinary/org_incineration#28]
Sub-issue of #22

**Comment by shreyansh-g24** [comment]
Table: incineration_records

Fields:
  1. timestamps
  2. string: organization_subdomain (Subdomain of the organization on which incineration was run)
  3. string: exception_raised (Exception raised in the process, if any)
  4. array: ordered_models (Ordered list of models to be incinerated)
  5. jsonb: configuration (The configuration with which the incineration was run, SKIPPED_MODELS, MODELS_REQUIRE_DESTROY, CYCLIC_DEPENDENCIES and associated_models list)

If there is an exception, it would also send an error to honeybadger, eventually.

**Comment by shreyansh-g24** [comment]
@unnitallman Please let me know your thoughts.

**Comment by unnitallman** [comment]
@shreyansh-g24 Looks good to me.
