### ISSUE TITLE
Not able to remove records from models which are not part of main application

### ISSUE THREAD

**Issue by mayanksharma4132** [bigbinary/org_incineration#47]
https://vimeo.com/715582479/9e16ed9fbf

cc @unnitallman

**Comment by shreyansh-g24** [comment]
One way to fix it is:
  - As @mayanksharma4132 showed, we can explicitly destroy the records for `AnyEngine::Models` in the `incinerable_concern.rb`.

A better way, I think, would be to setup the `Engine::Models` to inherit from `::ApplicationRecord` class as a rule, this way they would be included in `::ApplicationRecord.descendants`

@akhil-gautam 
cc @unnitallman

**Comment by unnitallman** [comment]
@shreyansh-g24 Instead of `Organization.super_class` what if we go for `ActiveRecod::Base` ? https://github.com/bigbinary/org_incineration/blob/master/lib/org_incineration/dependency_sorter.rb

**Comment by shreyansh-g24** [comment]
@unnitallman Yes that should catch all the `ApplicationRecord` instances allowing us to further traverse down their descendants separately.

**Comment by shreyansh-g24** [comment]
@mayanksharma4132 @akhil-gautam 

Please remove the following models from `incinerable_concern.rb` config

```ruby
      # "Tag": {
        #   joins: {},
        #   where: ["tags.organization_id = ?", org_id]
        # },

        # "Widget::ConversationTag": {
        #   joins: {},
        #   where: ["tags.organization_id = ?", org_id]
        # },

        # "Sms::ConversationTag": {
        #   joins: {},
        #   where: ["tags.organization_id = ?", org_id]
        # },

        # "Insights::VisitorTag": {
        #   joins: {},
        #   where: ["tags.organization_id = ?", org_id]
        # },
```

and add `NeetoTags::Tag`

```ruby
      "NeetoTags::Tag": {
          joins: {},
          where: ["organization_id = ?", org_id]
        },
```

**Comment by akhil-gautam** [comment]
@shreyansh-g24 Removed in https://github.com/bigbinary/neeto-chat-web/pull/3854.
