### ISSUE TITLE
Tags controller related error showing up during incineration

### ISSUE THREAD

**Issue by yedhink** [bigbinary/org_incineration#52]
https://www.loom.com/share/d56f93489a454383803ae1d730b11636

@shreyansh-g24 _a Please take a look. Seems to be originating from https://github.com/bigbinary/neeto_tags

Use the following PR branch for debugging this issue: https://github.com/bigbinary/neeto-wheel-dummy/pull/1

cc: @unnitallman

**Comment by shreyansh-g24** [comment]
@yedhink _a `neeto-tags` expects the host application to have an `Api::V1::BaseController` which is missing from `neeto-wheel`, that is why you are getting this issue.

**Comment by yedhink** [comment]
Thanks Shreyansh for finding the root cause.

I have raised an issue for this in neetoTags. Closing this issue.
