### ISSUE TITLE
Updating the readme with some extra sections

### ISSUE THREAD

**Issue by AlanLoovees** [bigbinary/org_incineration#56]
In the README, lets add sections like these (some of which are already present):

- What is Incineration?
- Need of Incineration.
- Installation (covered)
- Explanation on things to write in `incinerable_concern` (covered under Usage)
- How to test the incineration locally
- Development (covered)
- Contributing (covered)
- License (covered)
- Code of Conduct (covered)

I think it would be helpful from a beginner’s point of view and keep things simple. We can also split it out into multiple docs and keep in the `docs` folder and link it in README.

**Comment by yedhink** [comment]
Closing in favor of #57
