### ISSUE TITLE
Make the README more readable

### ISSUE THREAD

**Issue by yedhink** [bigbinary/org_incineration#57]
When a beginner starts out in the neeto ecosystem and if they run into issues or want to tinker around with this gem, then the docs should help them. At the moment the doc is not very beginner friendly.

As pointed by Alan, the following section segregation would help https://github.com/bigbinary/org_incineration/issues/56#issue-1317831792.

@AlanLoovees _a Please take this up. Write the doc in a simple yet concise manner. Let's provide this doc as a reference for other neeto gems so that they can update their docs too.

cc: @shreyansh-g24

**Comment by shreyansh-g24** [comment]
@yedhink I will take this up following #55 
cc @AlanLoovees
