### ISSUE TITLE
Add `ActionText::EncryptedRichText` under ignored rails models

### ISSUE THREAD

**Issue by abhishekt98** [bigbinary/org_incineration#62]
After upgrading rails getting the following error in incineration service. We should add `ActionText::EncryptedRichText` in skipped models under ignored rails models category.

<img width="1126" alt="Screenshot 2022-08-03 at 10 16 00 PM" src="https://user-images.githubusercontent.com/47141466/182663869-fb290955-438b-47ff-943d-9540b8a7335c.png">

cc: @unnitallman

**Comment by abhishekt98** [comment]
@shreyansh-g24 _a

**Comment by shreyansh-g24** [comment]
@abhishekt98 _a Can you please try again after updating the gem?

**Comment by abhishekt98** [comment]
@shreyansh-g24 It's working. Closing the issue
