### ISSUE TITLE
Incinerator does not work for following projects

### ISSUE THREAD

**Issue by sandip-mane** [bigbinary/org_incineration#65]
Reasons:
1. Organization model's default scope is not unscoped hence incineration does not work
2. Cyclic dependencies are not cleared sometimes

### Reason 1 & 2:
- [ ] https://github.com/bigbinary/neeto-desk-web/issues/14782
**PR with failing test**: https://github.com/bigbinary/neeto-desk-web/pull/14835

### Reason 1:
- [ ] https://github.com/bigbinary/neeto-kb-web/issues/3108
**PR with failing test**: https://github.com/bigbinary/neeto-kb-web/pull/3145

**Comment by sandip-mane** [comment]
@abhishekt98 _a

**Comment by abhishekt98** [comment]
@sandip-mane About the first issue: The model is actually unscoped in the incineration service. The test is failing in Desk and KB only because of the second issue. One problem found in the test is instead of using 
```
assert_difference "Organization.count", -1 do
   organization.incinerate!
end
```
 we should use 
```
assert_difference "Organization.unscoped.count", -1 do
   organization.incinerate!
end
```
 as we are incinerating a cancelled organization.

**Comment by abhishekt98** [comment]
@shreyansh-g24 
Reason 2: This issue is similar to https://github.com/bigbinary/neeto-course-web/issues/1235. Should I follow the same fix or do wee need to add any fix in the gem?

**Comment by shreyansh-g24** [comment]
@abhishekt98 Please follow the same fix. Most likely it would be a similar error that can be fixed by updating the associations and/or incineration configuration.
